name: Push 3 Python Codes in 3 Days

on:
  schedule:
    - cron: "0 5 * * *"  # Runs daily at 5:00 AM UTC (10:30 AM IST)
  workflow_dispatch:

jobs:
  push-codes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "your-email@example.com"

      - name: Commit today's Python code
        run: |
          START_DATE="2025-07-18"
          DAY=$(( ( $(date +%s) - $(date -d "$START_DATE" +%s) ) / 86400 + 1 ))

          if [ $DAY -eq 1 ]; then
            cp trip_codes/day1.py day1.py
            git add day1.py
            git commit -m "Add Day 1 Python code"
            git push
          elif [ $DAY -eq 2 ]; then
            cp trip_codes/day2.py day2.py
            git add day2.py
            git commit -m "Add Day 2 Python code"
            git push
          elif [ $DAY -eq 3 ]; then
            cp trip_codes/day3.py day3.py
            git add day3.py
            git commit -m "Add Day 3 Python code"
            git push
          else
            echo "3-day window complete. No commits."
